@startuml
[*] --> STATE_INIT
STATE_INIT -> STATE_WAIT : IXFEvent::Initial
STATE_WAIT --> STATE_POSCHANGED : IXFEvent::Event && EventID == JOYSTICK_POSCHANGED_EVENT
STATE_POSCHANGED --> STATE_WAIT : XFNullTransition()
@enduml